name: golangci-lint

on:
  push:
    branches: [ "dungeon-master", "master", "main" ]
  pull_request:
    branches: [ "dungeon-master", "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: "1.23"

      - name: Lint using golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.55.2
          working-directory: ./