name: Test and coverage

on:
  push:
    branches: [ "dungeon-master", "master", "main" ]
  pull_request:
    branches: [ "dungeon-master", "master", "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: "1.23"

      - name: Run tests with coverage
        run: go test -v ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: Run tests -race
        run: go test -v ./... -race

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: MisterZurg/TBank-backend-academy-URL-Shortener